version: '3.7'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD_PLACEHOLDER
      MYSQL_DATABASE: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  app:
    build: .
    ports:
      - "10101:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
